name: restaurant_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  http: ^1.3.0
  lottie: ^3.3.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0

dev_dependencies:
  test: ^1.25.15
  mocktail: ^1.0.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/loading.json
    - assets/animations/error.json
    - assets/animations/not_found.json
    - assets/animations/empty.json
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
